class AppStrings {
  static const String friend = 'Friends';
  static const String userNames = 'User Name';
  static const String group = 'Group';
  static const String profile = 'Profile';
  static const String more = 'More';
  static const String themes = 'Themes';
  static const String chat = 'Chats';
  static const String call = 'Calls';
  static const String callNow = 'Call Now';
  static const String settings = 'Settings';
  static const String privacy = 'Privacy';
  static const String logOut = 'Logout';
  static const String manage = 'Manage';
  static const String about = 'About';
  static const String welcome = 'Welcome!';
  static const String version = 'App Version: ';
  static const String versionNumber = '1.0.0';
  static const String phone = '85593973138';
  static const String homeScreen = 'Home Screen';
  static const String profileScreen = 'Profile Screen';
  static const String inviteFriends = 'Invite Friends to FoxTalk';
  static const String allMessages = 'All Messages';
  static const String makeCall = 'Make calls to your friends';
  static const String youRecent = 'You recent history will be listed here';
  static const String verificationCodeHint = 'We have sent you a verification code to your: ';
  static const String youCanCheckBox = ' Your can check in box.';
  static const String resendVerificationCode = 'Didn\'t receive the code? Send again';
}
